from .task import Task
from .task_01_update_repo import UpdateRepo
from .task_02_openssh_server_install import OpenSSHServerInstall
from .task_03_disable_auto_mounting import DisableAutoMounting
from .task_04_livecd_zfs_install import LiveCDZfsInstall
